// SPDX-License-Identifier: Apache-2.0

package com.kylemayes.generator.generate

import com.kylemayes.generator.generate.file.generateBitfields
import com.kylemayes.generator.generate.file.generateBitmasks
import com.kylemayes.generator.generate.file.generateBuilders
import com.kylemayes.generator.generate.file.generateCommandStructs
import com.kylemayes.generator.generate.file.generateCommands
import com.kylemayes.generator.generate.file.generateConstants
import com.kylemayes.generator.generate.file.generateEnums
import com.kylemayes.generator.generate.file.generateExtensionTraits
import com.kylemayes.generator.generate.file.generateExtensions
import com.kylemayes.generator.generate.file.generateFunctions
import com.kylemayes.generator.generate.file.generateHandles
import com.kylemayes.generator.generate.file.generateLib
import com.kylemayes.generator.generate.file.generateMacros
import com.kylemayes.generator.generate.file.generateResultEnums
import com.kylemayes.generator.generate.file.generateStructs
import com.kylemayes.generator.generate.file.generateTypedefs
import com.kylemayes.generator.generate.file.generateUnions
import com.kylemayes.generator.generate.file.generateVersionTraits
import com.kylemayes.generator.generate.file.generateVkModule
import com.kylemayes.generator.generate.file.generateWrapperModule
import com.kylemayes.generator.registry.Registry
import com.kylemayes.generator.support.rustfmt
import mu.KotlinLogging
import java.nio.file.Files
import java.nio.file.Path

private val log = KotlinLogging.logger { /* */ }

/** Generates Rust files for a Vulkan API registry. */
fun generateRustFiles(
    registry: Registry,
) = listOf(
    generateRustFile("generated-crate", "vk/bitmasks.rs", registry.generateBitmasks()),
    generateRustFile("generated-crate", "vk/commands.rs", registry.generateCommands()),
    generateRustFile("generated-crate", "vk/constants.rs", registry.generateConstants()),
    generateRustFile("generated-crate", "vk/enums.rs", registry.generateEnums()),
    generateRustFile("generated-crate", "vk/extensions.rs", registry.generateExtensions()),
    generateRustFile("generated-crate", "vk/functions.rs", registry.generateFunctions()),
    generateRustFile("generated-crate", "vk/handles.rs", registry.generateHandles()),
    generateRustFile("generated-crate", "vk/macros.rs", registry.generateMacros()),
    generateRustFile("generated-crate", "vk/result_enums.rs", registry.generateResultEnums()),
    generateRustFile("generated-crate", "vk/structs.rs", registry.generateStructs()),
    generateRustFile("generated-crate", "vk/typedefs.rs", registry.generateTypedefs()),
    generateRustFile("generated-crate", "vk/unions.rs", registry.generateUnions()),
    generateRustFile("generated-crate", "vk.rs", registry.generateVkModule()),
    generateRustFile("generated-crate", "wrapper/builders.rs", registry.generateBuilders()),
    generateRustFile("generated-crate", "wrapper/command_structs.rs", registry.generateCommandStructs()),
    generateRustFile("generated-crate", "wrapper/extension_traits.rs", registry.generateExtensionTraits()),
    generateRustFile("generated-crate", "wrapper/version_traits.rs", registry.generateVersionTraits()),
    generateRustFile("generated-crate", "wrapper.rs", registry.generateWrapperModule()),
    generateRustFile("generated-crate", "bitfields.rs", registry.generateBitfields()),
    generateRustFile("generated-crate", "lib.rs", registry.generateLib()),
)

/** A generated Rust file. */
data class File(
    val path: Path,
    var contents: String,
    var matches: Boolean? = null,
) {
    /** Attempts to format this generated Rust file. */
    fun format(): Boolean {
        return try {
            contents = rustfmt(contents)
            true
        } catch (e: Throwable) {
            log.error { "$path could not be formatted." }
            e.printStackTrace(System.err)
            false
        }
    }

    /** Writes this generated Rust file to disk. */
    fun write(directory: Path) {
        if (matches != true) {
            log.info { "Writing $path..." }
            Files.writeString(directory.resolve(path), contents)
        }
    }
}

/** Generates a Rust file for one of the Rust crates. */
private fun generateRustFile(
    crate: String,
    name: String,
    contents: String,
): File {
    val path = Path.of(crate).resolve("src").resolve(name)
    log.info { "Generating $path..." }
    return File(path, "$PREFIX\n$contents".replace(Regex("\\r\\n?"), "\n"))
}

/** The Rust file prefix. */
private const val PREFIX =
    """
// SPDX-License-Identifier: Apache-2.0

// DO NOT EDIT.
//
// This file has been generated by the Kotlin project in the `generator`
// directory from a Vulkan API registry.

#![allow(
    non_camel_case_types,
    non_snake_case,
    clippy::bad_bit_mask,
    clippy::let_unit_value,
    clippy::missing_safety_doc,
    clippy::missing_transmute_annotations,
    clippy::needless_lifetimes,
    clippy::too_many_arguments,
    clippy::type_complexity,
    clippy::unnecessary_cast,
    clippy::upper_case_acronyms,
    clippy::useless_transmute
)]
    """
